/**
 * Trains the intent model: a multinomial logistic regression over hashed
 * character n-grams that turns a kid's sentence into one of the labels the
 * building generator understands. Writes src/engine/chat/intentWeights.ts.
 *
 * Run: npm run train:intent
 *
 * It is small on purpose (2048 buckets × 29 labels, quantised to one byte
 * each) so it ships inside the bundle: no download, no network, and the
 * same answer on a phone as on a desktop.
 */

import { writeFileSync } from 'node:fs';
import { buildCorpus, rng } from '../src/engine/chat/intentCorpus.ts';
import { FEATURE_BUCKETS, INTENT_LABELS, featurize } from '../src/engine/chat/intentFeatures.ts';

const EPOCHS = 30;
const LEARNING_RATE = 0.5;
const L2 = 1e-6;
/** Share of the weights zeroed before shipping. */
const PRUNE = Number(process.env.PRUNE ?? 0.9);
const L = INTENT_LABELS.length;

const corpus = buildCorpus();
const rand = rng(7);
// Featurize once; the model sees the same vectors every epoch.
const data = corpus.map((s) => ({ x: [...featurize(s.text)], y: INTENT_LABELS.indexOf(s.label) }));
const holdoutAt = Math.floor(data.length * 0.9);
for (let i = data.length - 1; i > 0; i--) {
  const j = Math.floor(rand() * (i + 1));
  [data[i], data[j]] = [data[j], data[i]];
}
const train = data.slice(0, holdoutAt);
const test = data.slice(holdoutAt);

const w = new Float64Array(L * FEATURE_BUCKETS);
const b = new Float64Array(L);

function scores(x: Array<[number, number]>): Float64Array {
  const out = new Float64Array(L);
  for (let l = 0; l < L; l++) {
    let sum = b[l];
    const row = l * FEATURE_BUCKETS;
    for (const [bucket, value] of x) sum += w[row + bucket] * value;
    out[l] = sum;
  }
  return out;
}

function softmax(z: Float64Array): Float64Array {
  let max = -Infinity;
  for (const v of z) max = Math.max(max, v);
  let total = 0;
  const out = new Float64Array(z.length);
  for (let i = 0; i < z.length; i++) {
    out[i] = Math.exp(z[i] - max);
    total += out[i];
  }
  for (let i = 0; i < z.length; i++) out[i] /= total;
  return out;
}

console.log(`${corpus.length} sentences, ${L} labels, ${FEATURE_BUCKETS} buckets`);
for (let epoch = 0; epoch < EPOCHS; epoch++) {
  const rate = LEARNING_RATE * (1 - epoch / (EPOCHS + 2));
  let loss = 0;
  for (let i = train.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [train[i], train[j]] = [train[j], train[i]];
  }
  for (const { x, y } of train) {
    const p = softmax(scores(x));
    loss -= Math.log(Math.max(1e-9, p[y]));
    for (let l = 0; l < L; l++) {
      const g = p[l] - (l === y ? 1 : 0);
      if (g === 0) continue;
      const row = l * FEATURE_BUCKETS;
      for (const [bucket, value] of x) {
        const at = row + bucket;
        w[at] -= rate * (g * value + L2 * w[at]);
      }
      b[l] -= rate * g;
    }
  }
  if (epoch % 5 === 4 || epoch === EPOCHS - 1) console.log(`epoch ${epoch + 1}: loss ${(loss / train.length).toFixed(4)}`);
}

const accuracy = (set: typeof data): number => {
  let right = 0;
  for (const { x, y } of set) {
    const z = scores(x);
    let best = 0;
    for (let l = 1; l < L; l++) if (z[l] > z[best]) best = l;
    if (best === y) right++;
  }
  return right / set.length;
};
console.log(`train accuracy ${(accuracy(train) * 100).toFixed(1)}%, held out ${(accuracy(test) * 100).toFixed(1)}%`);

// Most buckets say nothing about most labels. Zeroing the smallest weights costs
// almost no accuracy and makes the shipped file compress to a fraction of its size.
const magnitudes = Float64Array.from(w, Math.abs).sort();
const cut = magnitudes[Math.floor(magnitudes.length * PRUNE)];
let pruned = 0;
for (let i = 0; i < w.length; i++) {
  if (Math.abs(w[i]) <= cut) {
    w[i] = 0;
    pruned++;
  }
}
console.log(`pruned ${((pruned / w.length) * 100).toFixed(0)}% of the weights; held out now ${(accuracy(test) * 100).toFixed(1)}%`);

// Quantise to one byte per weight: the scale is the largest magnitude.
let scale = 0;
for (const v of w) scale = Math.max(scale, Math.abs(v));
scale /= 127;
const bytes = new Uint8Array(w.length);
for (let i = 0; i < w.length; i++) bytes[i] = Math.round(Math.max(-127, Math.min(127, w[i] / scale))) + 128;
const base64 = Buffer.from(bytes).toString('base64');

const file = `// Generated by scripts/train-intent.ts — do not edit by hand.
// Intent model: ${FEATURE_BUCKETS} hashed n-gram buckets → ${L} labels (softmax),
// one byte per weight. Trained on ${corpus.length} generated sentences;
// held-out accuracy ${(accuracy(test) * 100).toFixed(1)}% with ${((pruned / w.length) * 100).toFixed(0)}% of the weights pruned to zero.
import type { IntentWeights } from './intent';

export const INTENT_WEIGHTS: IntentWeights = {
  buckets: ${FEATURE_BUCKETS},
  labels: ${L},
  scale: ${scale.toExponential(6)},
  bias: [${[...b].map((v) => v.toFixed(4)).join(',')}],
  weights: '${base64}',
};
`;
writeFileSync(new URL('../src/engine/chat/intentWeights.ts', import.meta.url), file);
console.log(`wrote src/engine/chat/intentWeights.ts (${Math.round(base64.length / 1024)} KB of weights)`);
